openapi: 3.0.2
info:
  title: Sistema de Contratos - AZ Tecnologia
  description: API que fornece endpoints do sistema de contratos.
  contact:
    email: maria.mazo@azi.com.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: contratos
    description: API para Contratos
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /validacao-registro-empenho:
    get:
      tags:
        - contratos
      summary: Validação de registro de empenho.
      description: Endpoint para validar se poderá ser cadastrado um empenho no SIGEF.
      operationId: validacaoRegistroEmpenho
      parameters:
        - name: numeroIdentificador
          in: path
          description: Número Identificador do Contrato
          required: true
          schema:
            type: string
        - name: cnpjFornecedor
          in: path
          description: CNPJ do Fornecedor
          required: true
          schema:
            type: string
        - name: numeroDotacao
          in: path
          description: Número da Dotação
          required: true
          schema:
            type: string
        - name: valorEmpenho
          in: path
          description: Valor do empenho
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Requisição realizada com sucesso.
          content:
            application/json:
              example:
                mensagem: Validação realizada com sucesso. Registro de empenho validado.
        '404':
          description: Contrato não encontrado.
          content:
            application/json:
              example:
                exception: ContratoNaoEncontradoException
                mensagem: >-
                  O número de contrato informado não é válido. Verifique e tente
                  novamente.
        '422':
          description: Dados não processados corretamente.
          content:
            application/json:
              examples:
                Valor informado maior que planejado:
                  value:
                    exception: SomaEmpenhosUltrapassaValorPlanejadoException
                    mensagem: >-
                      Não foi possível cadastrar o empenho pois as somas dos
                      empenhos ultrapassa o valor planejado para o exercício.
                Dotação não correspondente:
                  value:
                    exception: DotacaoNaoCorrespondenteException
                    mensagem: >-
                      A dotação informada não corresponde à dotação do contrato.
                      Por favor, verifique e tente novamente.
  /validacao-anulacao-empenho:
    get:
      tags:
        - contratos
      summary: Validação de anulação de empenho.
      description: Endpoint para validar se poderá anular o empenho no SIGEF.
      operationId: validacaoAnulacaoEmpenho
      parameters:
        - name: idEmpenhoSIGEF
          in: path
          description: ID do empenho a ser anulado cadastrado no SIGEF
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Requisição realizada com sucesso.
          content:
            application/json:
              example:
                mensagem: Empenho pode ser anulado.
        '404':
          description: Empenho não encontrado no contratos
          content:
            application/json:
              example:
                exception: EmpenhoNaoEncontradoException
                mensagem: >-
                  O empenho informado não foi encontrado no sistema de
                  contratos.
        '422':
          description: Dados não processados corretamente.
          content:
            application/json:
              examples:
                Empenho vinculado à atesto:
                  value:
                    exception: EmpenhoVinculadoAtestoException
                    mensagem: >-
                      O empenho não pode ser anulado pois está vinculado ao
                      atesto nº XXX.
